### ISSUE TITLE
Update README to Use Public Repository for Poetry Source

### ISSUE THREAD

**Issue by huan-up** [NorthShoreAutomation/pythonik#1]
The README example for adding a Poetry source currently points to a private GitLab project:

```bash
poetry source add --priority=supplemental gitlab https://gitlab.com/api/v4/projects/51363622/packages/pypi/simple
```

Please update this to a public repository URL to improve accessibility.

**Comment by nsa-brant** [comment]
@huan-up thanks! this was fixed by some changes to the README for 0.6.2
